version: '3.2'

networks:
  yota_test_task:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.2.0.0/16"

services:        
  test-app:
    build: test-app
    container_name: yota-test-app
    ports:
      - '8090:8080'
    networks:
      yota_test_task:
          ipv4_address: 10.2.1.4
    restart: unless-stopped
